### ISSUE TITLE
Exception In Server Tick Loop - 1.19.4 - Fabric

### ISSUE THREAD

**Issue by TheIrishStud** [konwboj/Tumbleweed#35]
Seemed like everything was fine until I tried to break a passing tumbleweed... then got this crash error...

java.lang.NoSuchMethodError: 'net.minecraft.class_1282 net.minecraft.class_1282.method_5532(net.minecraft.class_1657)'
	at net.konwboy.tumbleweed.common.EntityTumbleweed.method_5698(EntityTumbleweed.java:393)
	at net.minecraft.class_1657.method_7324(class_1657.java:1190)
	at net.minecraft.class_3222.method_7324(class_3222.java:1485)
	at net.minecraft.class_3244$1.method_34218(class_3244.java:1610)
	at net.minecraft.class_2824$1.method_34213(class_2824.java:166)
	at net.minecraft.class_2824.method_34209(class_2824.java:66)
	at net.minecraft.class_3244.method_12062(class_3244.java:1571)
	at net.minecraft.class_2824.method_12251(class_2824.java:53)
	at net.minecraft.class_2824.method_11054(class_2824.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:10828)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:762)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:747)
	at net.minecraft.server.MinecraftServer.handler$bem000$carpet$modifiedRunLoop(MinecraftServer.java:12445)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by konwboj** [comment]
I released a 1.19.4 version which should fix it
